<Project>
  <PropertyGroup>
    <VcpkgEnableManifest>true</VcpkgEnableManifest>
    <VcpkgManifestRoot>$(MSBuildThisFileDirectory)</VcpkgManifestRoot>
    <VcpkgUseStatic>true</VcpkgUseStatic>
    <VcpkgUseMD>true</VcpkgUseMD>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <LanguageStandard>stdcpp23</LanguageStandard>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
