<Project>
  <PropertyGroup>
    <VcpkgEnableManifest>true</VcpkgEnableManifest>
    <VcpkgManifestRoot>$(MSBuildThisFileDirectory)</VcpkgManifestRoot>
    <VcpkgUseStatic>true</VcpkgUseStatic>
    <VcpkgUseMD>true</VcpkgUseMD>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <LanguageStandard>stdcpp23</LanguageStandard>
    </ClCompile>
  </ItemDefinitionGroup>

  <!-- Set FlenseBaseOutputPath to avoid container builds and VS builds overwriting each other -->
  <PropertyGroup Condition="'$(FlenseOutputDirectory)' != ''">
    <IntDir>$(FlenseOutputDirectory)\$(MSBuildProjectName)\$(Platform)\$(Configuration)\obj\</IntDir>
    <OutDir>$(FlenseOutputDirectory)\$(MSBuildProjectName)\$(Platform)\$(Configuration)\bin\</OutDir>
  </PropertyGroup>
</Project>
