import "Models/AllNotes.idl";

namespace Flense
{
    [default_interface]
    runtimeclass AllNotesPage : Microsoft.UI.Xaml.Controls.Page
    {
        AllNotesPage();
        Flense.Models.AllNotes NotesModel{ get; };
    }
}
