import "FilesystemChangeKind.idl";

namespace Flense
{
    runtimeclass FilesystemItemColourConverter : [default] Microsoft.UI.Xaml.Data.IValueConverter
    {
        FilesystemItemColourConverter();
    }
}
