import "FilesystemChangeKind.idl";

namespace Flense
{
    runtimeclass FilesystemItemColourConverter : [default] Microsoft.UI.Xaml.Data.IValueConverter
    {
        FilesystemItemColourConverter();

        Microsoft.UI.Xaml.Style AddedStyle;
        Microsoft.UI.Xaml.Style RemovedStyle;
        Microsoft.UI.Xaml.Style ModifiedStyle;
    }
}
