import "FilesystemChangeKind.idl";

namespace Flense
{
    runtimeclass FilesystemTreeNode
    {
        String Name { get; };
        Boolean IsDirectory { get; };
        FilesystemChangeKind ChangeKind { get; };
        Windows.Foundation.Collections.IObservableVector<FilesystemTreeNode> Children { get; };
    }
}
