import "FileKind.idl";
import "FilesystemChangeKind.idl";

namespace Flense
{
    [bindable]
    [default_interface]
    runtimeclass FilesystemTreeNode : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        String Name { get; };
        FileKind Kind { get; };
        FilesystemChangeKind ChangeKind { get; };
        UInt64 Size { get; };
        Single SizeAsProportionOfParent { get; };
        Microsoft.UI.Xaml.Thickness IndentMargin { get; };
        Boolean Visible { get; };
        Boolean IsExpanded;
        Windows.Foundation.Collections.IObservableVector<FilesystemTreeNode> Children { get; };
        Windows.Foundation.Collections.IObservableVector<FilesystemTreeNode> ChildrenIfExpanded { get; };
        Boolean HasChildren { get; };
    }
}
