import "FileKind.idl";
import "FilesystemChangeKind.idl";

namespace Flense
{
    runtimeclass FilesystemTreeNode
    {
        String Name { get; };
        FileKind Kind { get; };
        FilesystemChangeKind ChangeKind { get; };
        UInt64 Size { get; };
        Windows.Foundation.Collections.IObservableVector<FilesystemTreeNode> Children { get; };
    }
}
