namespace Flense
{
    [default_interface]
    runtimeclass FilesystemItemTemplateSelector : Microsoft.UI.Xaml.Controls.DataTemplateSelector
    {
        FilesystemItemTemplateSelector();

        Microsoft.UI.Xaml.DataTemplate FileTemplate;
        Microsoft.UI.Xaml.DataTemplate FolderTemplate;
    }
}
