import "FilesystemChangesViewModel.idl";
import "FilesystemChangeVisibility.idl";
import "FilesystemTreeNode.idl";

namespace Flense
{
    [default_interface]
    runtimeclass FilesystemChangesView : Microsoft.UI.Xaml.Controls.UserControl
    {
        FilesystemChangesView();

        FilesystemChangesViewModel ViewModel { get; };

        static Microsoft.UI.Xaml.DependencyProperty ItemsSourceProperty { get; };
        Windows.Foundation.Collections.IObservableVector<Flense.FilesystemTreeNode> ItemsSource;

        static Microsoft.UI.Xaml.DependencyProperty SearchQueryProperty { get; };
        String SearchQuery;

        static Microsoft.UI.Xaml.DependencyProperty ChangeVisibilityProperty { get; };
        FilesystemChangeVisibility ChangeVisibility;
    }
}
