namespace Flense
{
    [default_interface]
    runtimeclass ImageDetailsViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ImageDetailsViewModel();

        Windows.Storage.StorageFile ImageArchive;
        Windows.Foundation.Collections.IObservableVector<String> Filenames{ get; };

        Boolean IsLoading{ get; };
        Boolean IsLoaded{ get; };
        Double LoadingProgress{ get; };

        Windows.Foundation.IAsyncAction LoadAsync();
    }
}
