import "ImageDetailsViewModel.idl";
import "FilesystemChangeVisibility.idl";

namespace Flense
{
    [default_interface]
    runtimeclass ImageDetailsPage : Microsoft.UI.Xaml.Controls.Page
    {
        ImageDetailsPage();
        ImageDetailsViewModel ViewModel{ get; };

        static FilesystemChangeVisibility BuildChangeVisibility(
            Windows.Foundation.IReference<Boolean> showUnchanged,
            Windows.Foundation.IReference<Boolean> showAdded,
            Windows.Foundation.IReference<Boolean> showModified,
            Windows.Foundation.IReference<Boolean> showRemoved);
    }
}
