namespace Flense
{
    [default_interface]
    runtimeclass ImageDetailsPage : Microsoft.UI.Xaml.Controls.Page
    {
        ImageDetailsPage();
        Windows.Storage.StorageFile ImageFile;
    }
}
