import "ImageDetailsViewModel.idl";

namespace Flense
{
    [default_interface]
    runtimeclass ImageDetailsPage : Microsoft.UI.Xaml.Controls.Page
    {
        ImageDetailsPage();
        ImageDetailsViewModel ViewModel{ get; };
    }
}
