import "Models/Note.idl";

namespace Flense.Models
{
    runtimeclass AllNotes 
    {
        AllNotes();
        IObservableVector<Note> Notes{ get; };

        void AddNote(Flense.Models.Note note);
        void RemoveNote(Flense.Models.Note note);
    }
}
