namespace Flense.Models
{
    runtimeclass Note : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Note(String filename, String text, Windows.Foundation.DateTime date);

        String Text;
        String DisplayDate{ get; };

        Windows.Foundation.IAsyncAction SaveAsync();
        Windows.Foundation.IAsyncAction DeleteAsync();
    }
}